CREATE TABLE pro_users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(18) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    city VARCHAR(100) DEFAULT NULL,
    name VARCHAR(100) DEFAULT NULL,
    surname VARCHAR(100) DEFAULT NULL,
    patronym VARCHAR(100) DEFAULT NULL
)
